<a href="https://colab.research.google.com/github/miguelferrufino/data/blob/master/M2_AI1_FerrufinoMiguelAlumno17.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# M2_AI1_CONSUMO TELEFÓNICO
By: Miguel Marcelo Ferrufino Lopez - Alumno 17\
Master en Big Data & Data Science - Modulo 2, bloque 1. 

In [ ]:
# Importacion de librerias
import pandas as pd
import numpy as np

In [ ]:
# Carga del fichero desde enlace raw github y creacion del DF
url = 'https://raw.githubusercontent.com/miguelferrufino/data/master/consumo_telefonico.csv'

#Creacion del DF
df = pd.read_csv(url, sep=';')

#Visualizacion de la cabecera del DF
df.head()

cod_periodo cod_segmento  cod_tarifa  cod_cliente  cod_terminal consumo
0  01/01/2017         seg1         100         1850          1665    49,5
1  01/01/2017         seg1         100         3998          3598   13,25
2  01/01/2017         seg1         100         9216          8294   48,41
3  01/01/2017         seg1         100         5430          4887      27
4  01/01/2017         seg1         101          498           448   32,33

In [ ]:
# Resumen de informacion del fichero
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   cod_periodo   257 non-null    object
 1   cod_segmento  257 non-null    object
 2   cod_tarifa    257 non-null    int64 
 3   cod_cliente   257 non-null    int64 
 4   cod_terminal  257 non-null    int64 
 5   consumo       257 non-null    object
dtypes: int64(3), object(3)
memory usage: 12.2+ KB
None



Analisis del tipo de variables segun el diccionario y el analisis individual de cada una:

1.   cod_periodo: es el periodo en el que se realizó el informe. Dicha fecha contiene el año y el mes, en ese orden. La información siempre está al día 1 de cada mes. **Variable de tipo objeto almacenada de forma numerica de uso categorico**
2.   cod_segmento: los clientes están clasificados por diferentes segmentos en función del tipo de cliente y consumo que tienen. Hay 3 tipos de segmentos: promotor o bueno, pasivo o regular y detractor o malo. **Variable de tipo objeto almacenada de forma numerica de uso cualitativa ordinal**
3. cod_tarifa: la compañía tiene 5 tarifas distintas. Se clasifican con el código 100, 101, 102, 103 y 104. Se incluyen distintos servicios, desde la tarifa 100 como la más económica y con los servicios básicos hasta la tarifa 104 con los servicios más exclusivos que tiene la compañía. **Variable cualitativa ordinal**
4. cod_cliente: el cliente tiene un código identificador único, el cual está asociado a la tarifa y al consumo facturado que realiza. **Variable numerica de uso cualitativa ordinal**
5. cod_terminal: **Variable numerica discreta**
6. consumo: es el consumo del cliente, cuya unidad monetaria son los euros. Es una información correspondiente al mes del periodo extraído, ya que a todos los clientes se les cobra de manera mensual. **Variable cuantitativa continua**

ANALISIS DESDE EL PUNTO DE VISTA **ANÁLSIS DE DATOS**

In [ ]:
# Analisis de la variable cod_periodo
periodo = pd.unique(df['cod_periodo'])
periodo.sort()
print(periodo)

['01/01/2017' '01/02/2017' '01/03/2017' '01/04/2017' '01/05/2017']


cod_periodo se identifica como **variable cualitativa**, pese a ser recogida de forma numerica, ya que permite clasificar la información sobre el año y el mes en que se realizo el informe. Tambien se puede identificar que es una **variable categorica ordinal** porque sigue un orden segun la el año y el mes mas antiguo al más actual

In [ ]:
# Analisis de la variable cod_segmento
segmento = pd.unique(df['cod_segmento'])
segmento.sort()
print(segmento)

['seg1' 'seg2' 'seg3']


cod_segmento se identifica como variable estadistica cualitativa o categorica que permite clasificar la información sobre el segmento segun el tipo de cliente y consumo que tienen. Hay 3 tipos de segmentos: 'seg1', 'seg2' y 'seg3'. Tambien se puede identificar que es una variable **cualitativa ordinal** porque hay 3 tipos de segmentos que **sigen una jerarquia**: promotor o bueno, pasivo o regular y detractor o malo.

In [ ]:
# Analisis de la variable cod_tarifa
tarifa = pd.unique(df['cod_tarifa'])
tarifa.sort()
print(tarifa)

[100 101 102 103 104]


cod_tarifa, pese a ser una variable tipo int recogida de forma numerica, se identifica como **variable cualitativa o categorica** que permite clasificar la información sobre la tarifa desde la más economica (100) hasta la más exlusiva (104). Hay 3 tipos de segmentos: 'seg1', 'seg2' y 'seg3'. Tambien se puede identificar que es una **variable categorica ordinal** porque hay 3 tipos de segmentos que **siguen una jerarquia:** promotor o bueno, pasivo o regular y detractor o malo.

In [16]:
# Analisis de la variable cod_cliente
clientes = pd.unique(df['cod_cliente'])
clientes.sort()
print(clientes)

[ 143  159  201  227  288  295  359  426  444  461  495  498  532  612
  695  790  884 1033 1076 1088 1174 1216 1220 1234 1302 1303 1441 1460
 1484 1571 1651 1665 1761 1778 1791 1798 1850 1879 1898 1914 1983 1987
 2082 2090 2114 2213 2240 2244 2305 2339 2347 2434 2689 2706 2708 2719
 2726 2729 2746 2874 2891 2908 2910 2942 2953 2988 3060 3170 3211 3252
 3267 3311 3313 3353 3413 3491 3512 3585 3629 3719 3722 3753 3789 3847
 3848 3858 3876 3899 3910 3990 3998 4048 4111 4123 4186 4207 4214 4227
 4248 4356 4378 4379 4380 4398 4528 4534 4535 4544 4562 4606 4700 4751
 4758 4855 4920 4930 4945 5030 5031 5035 5100 5105 5113 5120 5158 5188
 5224 5411 5430 5434 5470 5524 5529 5566 5572 5586 5618 5654 5712 5718
 5748 5760 5818 5819 5826 5897 5906 6011 6064 6072 6083 6201 6202 6205
 6213 6270 6288 6313 6342 6345 6347 6400 6437 6454 6506 6538 6547 6580
 6582 6658 6680 6693 6696 6795 6798 6807 6812 6833 6853 6862 6882 6893
 6921 7021 7232 7238 7268 7284 7318 7325 7340 7419 7541 7548 7658 7663
 7665 

cod_cliente es una variable numerica discreta, que tiene algunos saltos de numeracion que la hace no consecutiva en muchos casos. Filtraremos por los codigos de cliente mayores a 4000 para observar mas a detalle.

In [19]:
filtro_clientes = [col for col in clientes if col>4000]

print(filtro_clientes)

[4048, 4111, 4123, 4186, 4207, 4214, 4227, 4248, 4356, 4378, 4379, 4380, 4398, 4528, 4534, 4535, 4544, 4562, 4606, 4700, 4751, 4758, 4855, 4920, 4930, 4945, 5030, 5031, 5035, 5100, 5105, 5113, 5120, 5158, 5188, 5224, 5411, 5430, 5434, 5470, 5524, 5529, 5566, 5572, 5586, 5618, 5654, 5712, 5718, 5748, 5760, 5818, 5819, 5826, 5897, 5906, 6011, 6064, 6072, 6083, 6201, 6202, 6205, 6213, 6270, 6288, 6313, 6342, 6345, 6347, 6400, 6437, 6454, 6506, 6538, 6547, 6580, 6582, 6658, 6680, 6693, 6696, 6795, 6798, 6807, 6812, 6833, 6853, 6862, 6882, 6893, 6921, 7021, 7232, 7238, 7268, 7284, 7318, 7325, 7340, 7419, 7541, 7548, 7658, 7663, 7665, 7784, 7867, 7900, 7908, 7940, 7951, 8023, 8044, 8070, 8086, 8138, 8172, 8193, 8201, 8295, 8534, 8745, 8769, 8875, 8928, 9005, 9059, 9099, 9106, 9134, 9142, 9171, 9174, 9216, 9247, 9312, 9351, 9371, 9376, 9408, 9419, 9447, 9464, 9469, 9475, 9484, 9486, 9560, 9570, 9636, 9641, 9683, 9719, 9724, 9733, 9768, 9781, 9899, 9908, 9937, 9947, 9987]


Despues de observar **cod_cliente** a detalle y analizar la forma en que se recogio los datos, se define  como **variable cualitativa o categorica** que permite clasificar con un identificador unico a cada cliente. Esto debido a un detalle importante que es que esta variable esta asociada a la tarifa y consumo que realiza el cliente, por lo tanto se podria deducir que es una **variable cualitativa ordinal**.

In [20]:
# Analisis de la variable cod_terminal
terminal = pd.unique(df['cod_terminal'])
terminal.sort()
print(terminal)

[ 129  143  181  204  259  266  323  383  400  415  446  448  479  551
  626  711  796  930  968  979 1057 1094 1098 1111 1172 1173 1297 1314
 1336 1414 1486 1499 1585 1600 1612 1618 1665 1691 1708 1723 1785 1788
 1874 1881 1903 1992 2016 2020 2075 2105 2112 2191 2420 2435 2437 2447
 2453 2456 2471 2587 2602 2617 2619 2648 2658 2689 2754 2853 2890 2927
 2940 2980 2982 3018 3072 3142 3161 3227 3266 3347 3350 3378 3410 3462
 3463 3472 3488 3509 3519 3591 3598 3643 3700 3711 3767 3786 3793 3804
 3823 3920 3940 3941 3942 3958 4075 4081 4082 4090 4106 4145 4230 4276
 4282 4370 4428 4437 4451 4527 4528 4532 4590 4595 4602 4608 4642 4669
 4702 4870 4887 4891 4923 4972 4976 5009 5015 5027 5056 5089 5141 5146
 5173 5184 5236 5237 5243 5307 5315 5410 5458 5465 5475 5581 5582 5585
 5592 5643 5659 5682 5708 5711 5712 5760 5793 5809 5855 5884 5892 5922
 5924 5992 6012 6024 6026 6116 6118 6126 6131 6150 6168 6176 6194 6204
 6229 6319 6509 6514 6541 6556 6586 6593 6606 6677 6787 6793 6892 6897
 6899 

cod_terminal se define como **variable numerica discreta** no consecutiva que permite definir la terminal. Para el analisis de datos se la considera una **variable que no nos permite medir nada**, por lo tanto se considera una **variable cualitativa ordinal** ya que sigue un orden de menor a mayor.

In [21]:
# Analisis de la variable consumo
consumo_cliente = pd.unique(df['consumo'])
consumo_cliente.sort()
print(consumo_cliente)

['1' '10' '10,25' '10,36' '10,5' '10,8' '11' '11,63' '12' '13' '13,25'
 '13,33' '13,5' '13,61' '14' '14,22' '14,25' '14,42' '15' '15,2' '15,26'
 '16' '17' '17,5' '18' '18,32' '18,36' '19' '20' '21' '21,33' '21,44'
 '21,5' '22' '22,25' '23' '23,7' '24' '24,33' '24,6' '24,8' '25' '25,32'
 '25,33' '25,55' '25,8' '26' '26,45' '27' '27,35' '28' '28,55' '28,9'
 '29,3' '30' '30,11' '30,54' '31' '31,3' '31,44' '32' '32,3' '32,33'
 '32,7' '33' '33,25' '33,31' '34' '35' '35,3' '35,33' '35,41' '35,58' '36'
 '37' '38' '38,2' '38,35' '39' '39,45' '4,5' '40' '40,25' '41' '41,5' '42'
 '42,22' '43' '43,26' '44' '44,15' '44,6' '45' '45,33' '45,36' '46'
 '46,32' '47' '47,55' '47,58' '48' '48,41' '48,5' '49' '49,5' '49,52' '50'
 '50,25' '52,5' '55,2' '62,58' '63,28' '65,3' '66,32' '66,5' '66,54' '7'
 '70,14' '70,25' '72,3' '72,4' '75,33' '80,6' '82,3' '9' '9,6' '90,5'
 '91,2' '92,1' '95,12' '98,25' '98,5']


Se observa que la variable consumo es una **variable cuantitativa continua** que nos permite **medir el consumo** telefonico de cada cliente.